### Load in NumPy (remember to pip install numpy first)

In [12]:
import numpy as np

### The Basics

In [25]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [27]:
# Get Dimension
a.ndim

1

In [28]:
# Get Shape
b.shape

(2, 3)

In [29]:
# Get Type
a.dtype

dtype('int16')

In [30]:
# Get Size
a.itemsize

2

In [31]:
# Get total size
a.nbytes

6

In [32]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [33]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
# Get a specific element [r, c]
a[1, 5]

13

In [35]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [37]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [38]:
a[1,5] = 20
a[:,2] = 5
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [39]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in)
b[0,1,1]
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [41]:
# replace
b[:,1,:] = [[9,9],[8,8]]

In [42]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3)) #

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [43]:
# Any other number
np.full((2,2), 99, dtype='int16')

array([[99, 99],
       [99, 99]], dtype=int16)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2), np.random.random_sample(a.shape)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [45]:
# Random Integer values
np.random.randint(7, size=(3,3)), np.random.randint(-4,8, size=(3,3))

(array([[3, 6, 4],
        [2, 0, 3],
        [5, 2, 5]]),
 array([[ 4,  6, -1],
        [ 6, -3,  1],
        [ 0,  1,  2]]))

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [49]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
# output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [50]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [54]:
a + 2
a += 2

In [52]:
a - 2

array([-1,  0,  1,  2])

In [53]:
a * 2

array([2, 4, 6, 8])

In [56]:
a / 2

array([1, 0, 1, 0])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [ ]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [62]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, before.shape)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [104]:
import random
with open('data.txt', 'w') as f:
    for i in range(60):
        n = random.randint(1, 150)
        f.write(str(n)+',')
        if (i+1) % 6 == 0:
            print("new")
            f.write('\n')

new
new
new
new
new
new
new
new
new
new


In [105]:
with open('data.txt', 'r') as f:
    print(f.readlines())

['70,53,56,94,80,9,\n', '33,30,7,109,15,77,\n', '92,100,44,82,67,47,\n', '42,147,80,105,56,76,\n', '143,130,17,69,40,106,\n', '83,17,134,34,100,1,\n', '94,11,44,22,97,146,\n', '134,43,117,133,43,60,\n', '23,49,34,142,62,78,\n', '116,113,56,120,71,143,\n']


In [106]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[         70          53          56          94          80           9
  -2147483648]
 [         33          30           7         109          15          77
  -2147483648]
 [         92         100          44          82          67          47
  -2147483648]
 [         42         147          80         105          56          76
  -2147483648]
 [        143         130          17          69          40         106
  -2147483648]
 [         83          17         134          34         100           1
  -2147483648]
 [         94          11          44          22          97         146
  -2147483648]
 [        134          43         117         133          43          60
  -2147483648]
 [         23          49          34         142          62          78
  -2147483648]
 [        116         113          56         120          71         143
  -2147483648]]


##### Boolean Masking and Advanced Indexing

In [107]:
filedata[filedata > 50]

array([ 70,  53,  56,  94,  80, 109,  77,  92, 100,  82,  67, 147,  80,
       105,  56,  76, 143, 130,  69, 106,  83, 134, 100,  94,  97, 146,
       134, 117, 133,  60, 142,  62,  78, 116, 113,  56, 120,  71, 143],
      dtype=int32)

In [108]:
(~((filedata > 50) & (filedata < 100)))

array([[False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [False,  True,  True, False, False,  True,  True],
       [ True,  True, False,  True, False, False,  True],
       [ True,  True,  True, False,  True,  True,  True],
       [False,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True, False, False,  True],
       [ True,  True, False,  True, False,  True,  True]])

In [68]:
a = np.array([1,2,3,4,5])
a[[4,1]]

array([5, 2])

In [69]:
np.any(filedata > 50, axis=0)

NameError: name 'filedata' is not defined

In [ ]:
np.all(filedata > 50, axis=0)

In [71]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [72]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [74]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [75]:
a[[0,-1,-2], 3:]

array([[ 4,  5],
       [29, 30],
       [24, 25]])

In [90]:
10%10

0